# Generated by Django 6.0.3 on 2026-03-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarrCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Code', models.CharField(max_length=10, unique=True)),
                ('Category_Id', models.CharField(max_length=10)),
                ('Category_En', models.TextField()),
                ('Category_Zh', models.TextField()),
                ('Facility_En', models.TextField()),
                ('Facility_Zh', models.TextField()),
                ('Sorting_Order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line_Code', models.CharField(max_length=3)),
                ('Direction', models.CharField(max_length=10)),
                ('Station_Code', models.CharField(max_length=3)),
                ('Station_ID', models.IntegerField(unique=True)),
                ('Chinese_Name', models.TextField()),
                ('English_Name', models.TextField()),
                ('Sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Octopus_Card_Adult', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Octopus_Card_Student', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Octopus_Card_60', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Single_Ticket', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Octopus_Card_Children', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Octopus_Card_Elderly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Octopus_Card_Disabled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Single_Ticket_Children', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Single_Ticket_Elderly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Destination_Station_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Station_ID', to='mtrfare.station')),
                ('Destination_Station_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Station', to='mtrfare.station')),
                ('Source_Station_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_Station_ID', to='mtrfare.station')),
                ('Source_Station_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_Station', to='mtrfare.station')),
            ],
        ),
        migrations.CreateModel(
            name='BarrFac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.BooleanField()),
                ('AJTextEn', models.TextField(blank=True)),
                ('AJTextZh', models.TextField(blank=True)),
                ('Exit_Coordinate_X_Y', models.TextField(blank=True)),
                ('Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facility_Category', to='mtrfare.barrcat')),
                ('Station_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facility_In_Station', to='mtrfare.station')),
            ],
        ),
    ]
