# Generated by Django 6.0.3 on 2026-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtrfare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrcat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='barrcat',
            name='Item_Code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='Station_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
