# Generated by Django 6.0.3 on 2026-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtrfare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('pref_source_station_id', models.IntegerField()),
                ('pref_dest_station_id', models.IntegerField()),
                ('pref_barrier_free_facilities', models.TextField()),
            ],
        ),
    ]
